### ISSUE TITLE
Project Logo is missing.

### ISSUE THREAD

**Issue by heypoom** [DevForThaiFreedom/devforthaifreedom#3]
If you could create a logo for the project, please submit your designs into the `/designs/logo` directory.

**Comment by bkktimber** [comment]
I think the current design is quite ok.
anyway, the design could be better if we have guidelines, mood & tone for the designers.

Here are my quick ideas,

- the design should be inclusive for all people.
- represents the core values of the movement. (need a consensus here, could we go with Freedom, Equality, Fraternity?)

any ideas are welcome.

**Comment by heypoom** [comment]
I've updated the new logo and cover image from LunaNyan in the design/ directory. I'll add a new issue regarding the CI.
