### ISSUE TITLE
Main project website skeleton is missing.

### ISSUE THREAD

**Issue by heypoom** [DevForThaiFreedom/devforthaifreedom#5]
It would be great if we can generate a simple website skeleton, preferably using the markdown file as a data source. The requirement is that the project should be easy to contribute to everyone. Please use a static site generator with a minimal learning curve e.g. VuePress.

**Comment by pontakornth** [comment]
Could you assign me for this?

**Comment by heypoom** [comment]
Closed by #8. Thank you for your contribution!
